# Generated by Django 4.1.1 on 2022-10-18 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroa',
            fields=[
                ('dni', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=50)),
                ('abizena', models.CharField(max_length=50)),
                ('adina', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Kotxea',
            fields=[
                ('matrikula', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marka', models.CharField(max_length=100)),
                ('prezioa', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Alokairua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezero_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kotxea.bezeroa')),
                ('kotxe_matrikula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kotxea.kotxea')),
            ],
        ),
    ]
