# Generated by Django 4.1.1 on 2022-10-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotxea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezeroa',
            name='dni',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
