# Generated by Django 4.1.1 on 2022-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotxea', '0002_alter_bezeroa_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alokairua',
            name='alokairu_data_bukatu',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alokairua',
            name='alokairu_data_hasi',
            field=models.DateField(null=True),
        ),
    ]
